language: python
python:
    - "2.7"
    - "3.6"
    - "3.7"
before_script: pip install coveralls
script:
    - "coverage run --source=nukescripts_builder setup.py pytest"
after_success:
    - coveralls
