language: python
python:
    - "2.7"
    - "3.6"
    - "3.7-dev"
before_script: pip install coveralls
script:
    - "py.test"
    - "coverage run --source=nukescripts_builder setup.py test"
after_success:
    - coveralls
